"""
Django settings for ResumeAI project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

from pathlib import Path
from decouple import config, Csv
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="127.0.0.1,localhost",
).split(",")

# Production: Render sets RENDER=true and exposes the app's public host via
# RENDER_EXTERNAL_HOSTNAME. Append the Render host so a fresh production
# deploy works even before ALLOWED_HOSTS is hand-configured — without it every
# request is rejected with DisallowedHost (400) on the deploy domain. Render's
# blue/green deploy hostnames are always subdomains of onrender.com.
if os.environ.get("RENDER"):
    render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
    if render_host and render_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(render_host)
    if ".onrender.com" not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(".onrender.com")

ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]

# Origins allowed to POST CSRF-authenticated requests (needed on HTTPS
# hosts behind a proxy, e.g. Render). Comma-separated in .env, empty in dev.
CSRF_TRUSTED_ORIGINS = [
    origin
    for origin in config(
        "CSRF_TRUSTED_ORIGINS",
        default="",
        cast=Csv(),
    )
    if origin
]

# ── Production security (active only when DEBUG is off) ────────────────
# Behind Render's HTTPS proxy, correct https detection requires trusting the
# X-Forwarded-Proto header. SECURE_SSL_REDIRECT is deliberately NOT enabled:
# Render's internal health checks don't set X-Forwarded-Proto, so an http
# health probe would be 301-redirected forever and the service marked
# unhealthy. Render's public edge already serves HTTPS and can force
# http→https at the proxy if a strict redirect is ever required.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # 1 year; browsers only accept it over HTTPS. Safe once the site is
    # confirmed HTTPS-only, which Render's public edge is.
    SECURE_HSTS_SECONDS = 31536000


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Cloudinary
    "cloudinary",
    "cloudinary_storage",

    # Django REST Framework (API layer for the React frontend)
    "rest_framework",
    "corsheaders",

    # Your apps
    "account_manager",
    "dashboard",
    "resume",
    "core",
]

MIDDLEWARE = [
    # CORS first: must run before any middleware that can generate responses.
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ResumeAI.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ResumeAI.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Production safety: on Render, REQUIRE an explicit DATABASE_URL. Silently
# falling back to the bundled SQLite file would store all data on Render's
# ephemeral disk and lose it on the next deploy.
if os.environ.get("RENDER") and not config("DATABASE_URL", default=""):
    raise ImproperlyConfigured(
        "DATABASE_URL is required when running on Render. Set it to your "
        "Neon PostgreSQL connection string in the service environment."
    )

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"
# Static files are served through WhiteNoise via the "staticfiles" entry in
# STORAGES below (STATICFILES_STORAGE is removed in Django 6.0).


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "dashboard"

LOGOUT_REDIRECT_URL = "home"

# CORS — exact origins only. Never use CORS_ALLOW_ALL_ORIGINS or wildcard-like
# values. Normal development is same-origin (Vite proxies /api to Django), so
# the defaults cover the standalone Vite dev server (:5173) and the
# production-build preview server (:4173). Production: override
# CORS_ALLOWED_ORIGINS in the environment with the exact deployed frontend
# origin(s).
CORS_ALLOWED_ORIGINS = [
    origin
    for origin in config(
        "CORS_ALLOWED_ORIGINS",
        default=(
            "http://localhost:5173,"
            "http://127.0.0.1:5173,"
            "http://localhost:4173,"
            "http://127.0.0.1:4173"
        ),
        cast=Csv(),
    )
    if origin
]

# Django REST Framework — the API layer is JWT-only.
# Session auth for the server-rendered app is untouched (Django middleware /
# CsrfView stay active). DRF views are csrf_exempt by default, so JWT clients
# do not need CSRF tokens, and the two auth systems coexist cleanly.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    # JSON only: consistent API responses for React; no browsable HTML surface.
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
}

from datetime import timedelta

# SimpleJWT — tokens are signed with Django's SECRET_KEY (from .env).
# No refresh-token blacklisting: enabling it would require the
# token_blacklist app migration, which is out of scope for this task.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# Email Configuration (SMTP credentials live in .env)
# A blank EMAIL_HOST_USER disables outbound mail but keeps the app running.

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")

EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)

EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)

EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")

EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "noreply@resumeai.app"

# AI / OpenAI Configuration (optional; blank disables AI features)
# OPENAI_API_KEY lives in .env and is read by python-decouple.
# OPENAI_MODEL defaults to "gpt-4o-mini" if not set.
OPENAI_API_KEY = config("OPENAI_API_KEY", default="")
OPENAI_MODEL = config("OPENAI_MODEL", default="gpt-4o-mini")

# Development: when DEBUG=True and AI fails (e.g. quota exceeded), return
# mock AI data so the UI can be verified without a valid API key.
# NEVER enable in production.
DEBUG_AI = config("DEBUG_AI", default=DEBUG, cast=bool)

import cloudinary

# Cloudinary Configuration
# Safely handle potential missing credentials by only configuring if all exist.
cloudinary_cloud_name = config("CLOUDINARY_CLOUD_NAME", default="")
cloudinary_api_key = config("CLOUDINARY_API_KEY", default="")
cloudinary_api_secret = config("CLOUDINARY_API_SECRET", default="")

if os.environ.get("RENDER") and all([cloudinary_cloud_name, cloudinary_api_key, cloudinary_api_secret]):
    cloudinary.config(
        cloud_name=cloudinary_cloud_name,
        api_key=cloudinary_api_key,
        api_secret=cloudinary_api_secret,
        secure=True,
    )

    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.RawMediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Fallback to local storage if Cloudinary is misconfigured or not on Render
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Logging Configuration
# Ensures INFO-level logs (including our diagnostic logging) reach stdout/stderr
# in production environments like Render, so exceptions and pipeline stages are visible.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "resume": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}