# Generated by Django 5.2.16 on 2026-07-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
