# Generated by Django 5.2.16 on 2026-07-27 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.PositiveIntegerField(default=0)),
                ('job_match_score', models.PositiveIntegerField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='resume.resume')),
            ],
        ),
    ]
