# Generated by Django 5.2.16 on 2026-07-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resumeanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='improvement_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='job_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_descriptions/'),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
