# Generated by Django 5.2.16 on 2026-08-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resumeanalysis_improvement_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='resume_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
