# Generated by Django 5.2.16 on 2026-08-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resumeanalysis_resume_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='ai_explanation',
            field=models.JSONField(blank=True, default=dict, help_text='Cached AIExplanation response (JSON)'),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='ai_model',
            field=models.CharField(blank=True, default='gpt-4o-mini', help_text='OpenAI model used for cached AI responses', max_length=50),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='ai_prompt_version',
            field=models.PositiveIntegerField(default=2, help_text='Prompt version used for cached AI responses'),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='ai_rewrite',
            field=models.JSONField(blank=True, default=dict, help_text='Cached AIRewrite response (JSON)'),
        ),
    ]
